# Build pipeline
# More info at https://aka.ms/yaml

trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'src'
        Contents: 'index.html'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'